---
title: "Module Score"
format: html
editor: source
author: viv3kanand
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

## Load libraries

```{r}
#| label: packages
#| echo: true
#| eval: true
#| message: false
#| warning: false

require(Seurat)
require(tidyverse)

```

### Load data

```{r}
#| label: load data
#| echo: false
#| eval: true

seu_PBMC <- read_rds("../data/2024-11-22_seurat_obj_PBMC.rds")
DefaultAssay(seu_PBMC) <- "RNA"
Idents(seu_PBMC) <- "cell_type"

seu_WB <- read_rds("../data/2024-10-17_seurat_obj_WB.rds")
DefaultAssay(seu_WB) <- "RNA"
Idents(seu_WB) <- "cell_type"
seu_WB <- JoinLayers(seu_WB)

```


```{r}
# IFN pathway gene heatmap/scores

IFN <- c("TRANK1", "MOV10", "SMCHD1", "C19orf66", "TNK2", "NCF1", "ANKFY1", "C14orf159", "DDX60L", "PGAP1", "STAT2", "PNPT1", "ISG20", "RBCK1", "ZCCHC2", "SAMD4A", "PARP14", "RNF213", "PPM1K", "SAMD9", "SP100", "PARP11", "PRKD2", "PI4K2B", "TRIM14", "FTSJD2", "SCLT1", "SMTNL1", "CD38", "NT5C3", "PHF11", "ADAR", "PML", "SP110", "ZNFX1", "NUB1", "ZBP1", "ECE1", "PARP10", "TRIM22", "C6orf192", "TRIM5", "HSH2D", "TMEM229B", "PARP12", "SNTB1", "ZNF618", "STX17", "NADK", "ATP10A", "GTPBP1", "XRN1", "YEATS2", "TRIM56", "TDRD7", "IFI16", "DDX58", "SAMD9L", "N4BP1", "JAK2", "SPATS2L", "NMI", "DRAP1", "LGALS9", "SRGAP2", "APOL6", "CHST12", "TMEM140", "CNP", "FAM125A", "GMPR", "MX2", "HERC5", "GNB4", "LAG3", "DTX3L", "EIF2AK2", "TRIM25", "ABCD1", "HERC6", "DYNLT1", "DHX58", "OAS2", "RP4-697K14.7.1", "IFIH1", "GTPBP2", "GPR155", "APOL1", "UNC93B1", "FGD2", "SP140", "RIN2", "ACOT9", "NAPA", "UBA7", "DDX60", "LGALS3BP", "FAR2", "TLR3", "CHMP5", "IFI35", "MYD88", "OAS3", "UBE2L6", "AZI2", "TMEM62", "CBR1", "BAG1", "MLKL", "BRCA2", "MX1", "CXCL11", "CASP10", "TRIM21", "IFITM1", "PLSCR1", "BST2", "PARP9", "DBF4B", "IRF7", "C5orf56", "AXL", "PSMB9", "BLVRA", "RBM43", "C22orf28", "FMNL2", "CBWD2", "TREX1", "NEXN", "ISG15", "STAP1", "TRAFD1", "RASGRP3", "TNFSF10", "IFI44", "XAF1", "CD2AP", "SAT1", "RTP4", "GBP4", "IFIT5", "SLC38A5", "ZC3HAV1L", "RSAD2", "DISC1", "SCARB2", "CPNE5", "TOR1B", "OAS1", "USP18", "FRMD3", "OASL", "AGRN", "SSTR3", "GPD2", "LY6E", "TTC21A", "MUSTN1", "ETV7", "SPTLC2", "CDK18", "TAP2", "TNFSF13B", "EPSTI1", "IFIT2", "SCIMP", "FANCA", "CFH", "TAP1", "ATF5", "LAP3", "IFITM2", "C9orf91", "MAML2", "IL4I1", "HPSE", "HESX1", "MSR1", "IFIT1", "FAM46A", "KLHDC7B", "CMPK2", "RRBP1", "IFITM3", "APOBEC3A", "NFIX", "ODF2L", "IFI44L", "SIGLEC14", "JUP", "IFIT3", "EMP1", "DYSF", "OSBPL5", "SLFN13", "IFI6", "FBXO6", "OSBPL1A", "PRKCE", "TTC7B", "AIM2", "HSPA1B", "HSPA1A", "NDC80", "TYMP", "STAT1", "SSB", "MCOLN2", "SLFN5", "SCO2", "ASCL2", "IL1RN", "BAHCC1", "ATF3", "LRRC3", "LAMP3", "AKT1S1", "IL15RA", "IL18RAP", "ENDOD1", "IRF9", "SLFN12", "PLEKHN1", "WARS", "MYOF", "TLR7", "MASTL", "SECTM1", "GBP5", "HEG1", "LYN", "DSP", "GPBAR1", "MEFV", "FAM70A", "MT2A", "LILRA5", "FAM26F", "GBP1", "VAMP5", "SLFN12L", "GCH1", "ITSN1", "RUFY4", "GCNT1", "IL15", "SIGLEC1", "CXCL10", "LGALS2", "IFI27", "BUB1", "SERPING1", "FGL2", "GLT1D1", "IDO1", "PIWIL4", "ODF3B", "TCN2", "IGFBP4", "BATF2", "KIAA1522", "FFAR2", "IL1R2", "CCL8", "ABTB2", "MNDA", "RBMS2", "C7orf58", "CXCL9", "CCL13", "CCL7")

seu_WB <- JoinLayers(seu_WB)

seu_WB <- AddModuleScore(seu_WB, features = list(IFN), name = "IFN")


gene_sets <- msigdbr::msigdbr(species = "Homo sapiens")

neu_glist <- gene_sets[gene_sets$gs_name == "REACTOME_NEUTROPHIL_DEGRANULATION", ]$gene_symbol |> unique()

seu_WB <- AddModuleScore(seu_WB, features = list(neu_glist), name = "NEUD")
```



























