---
title: "Survival Analysis"
author: "viv3kanand"
format: html
editor: source
---

### Install packages

```{r}
#| label: install
#| echo: true
#| eval: false
options(renv.config.pak.enabled = TRUE)

renv::install("pharmaverse/ggsurvfit")
renv::install("survival")

```

### Load libraries

```{r}
#| label: packages
#| echo: true
#| eval: true
#| message: false
#| warning: false

require(DESeq2)
require(tidyverse)
require(survival)
require(ggsurvfit)
require(survminer)
```

### Load data

```{r}
#| label: load data
#| echo: false
#| eval: true

dds <- read_rds("RData/Bulk/2025-06-04_dds.rds")
ipa_m3 <- read_csv("../data/Bulk/IPA_M3_0.5FC.csv")
```

### Transform and filter data

```{r}
counts <- counts(dds, normalized = TRUE)

# filter genes whose expression is zero in more than half the samples
filter_fun <- function(x){
  x <- t(apply(as.matrix(x),1,as.numeric))
  r <- as.numeric(apply(x,1,function(i) sum(i == 0)))
  remove <- which(r > dim(x)[2]*0.5)
  return(remove)
}
remove <- filter_fun(counts)
counts <- counts[-remove,]
```

### Batch correction

```{r}
log_counts <- log2(counts + 1)

mm <- model.matrix(~Condition, colData(dds))
log_counts <- limma::removeBatchEffect(log_counts, batch=colData(dds)$Batch, design=mm)
```

### zscore calculation

```{r}
case_counts <- log_counts[, 1:52]

mean_n <- rowMeans(log_counts[, 53:64])
sd_n <- apply(log_counts[, 53:64], 1, sd)

# zscore scaling (broadcasting)
z_counts <- sweep(case_counts, 1, mean_n, FUN = "-")
z_counts <- sweep(z_counts, 1, sd_n, FUN = "/")

# z_counts <- z_counts[apply(z_counts, 2, function(x) any(is.infinite(x))),]
z_counts <- z_counts[apply(z_counts, 1, function(x) all(is.finite(x))), ]
```


```{r}
event_counts <- t(apply(z_counts, 1, function(x) ifelse(abs(x) > 1, 1, 0)))

event_counts <- t(apply(z_counts, 1, function(x) ifelse(x > 1,1,ifelse(x < -1,2,0))))

```


```{r}
meta <- colData(dds) |> as.data.frame()
```


```{r}
ind_meta <- which(rownames(meta) %in% colnames(z_counts))

prep_data <- function(gene) {
  meta[ind_meta,] |> 
    mutate(
      event = event_counts[gene,],
      group = ifelse(z_counts[gene,] >= (median(z_counts[gene,])), "High", "Low"),
      gene = gene
    ) |> 
    select(DD, HCM, event, group, gene)
}

gene_li <- ipa_m3[ipa_m3$Pathways == "Cardiac Hypertrophy Signaling (Enhanced)",]$Molecules |> strsplit(",") |> unlist()

plot_data <- map_dfr(gene_li, prep_data)

fits <- plot_data |> 
  group_split(gene) |> 
  map(~ survfit(Surv(DD, HCM) ~ group, data = .x))

names(fits) <- unique(plot_data$gene)

plots <- imap(fits, function(fit, gene_name) {
  df <- plot_data |> filter(gene == gene_name)
  
  P <- ggsurvplot(
    fit,
    data = df,
    risk.table = TRUE,
    pval = TRUE,
    pval.size = 3,
    palette = c("#CB477A", "#469FBF"),
    ggtheme = custom_theme(),
    title = gene_name,
    legend.title = "Expression")
  
  P$plot
})


fit_models <- function(gene) {
  meta_local <- meta[ind_meta,] |> mutate(expression = z_counts[gene,],
                               group = ifelse(z_counts[gene,] >= (median(z_counts[gene,])), 1,0))
  cox_model <- coxph(Surv(DD, HCM) ~ expression, data = meta_local)
  cox_summary <- summary(cox_model)

  surv_diff <- survdiff(Surv(DD, HCM) ~ group, data = meta_local)
  chisq <- surv_diff$chisq
  logrank_pval <- 1 - pchisq(chisq, df = length(surv_diff$n) - 1)
  
  tibble(
    gene = gene,
    coef = cox_summary$coefficients[1, "coef"],
    HR = cox_summary$coefficients[1, "exp(coef)"],
    CI_lower = cox_summary$conf.int[1, "lower .95"],
    CI_upper = cox_summary$conf.int[1, "upper .95"],
    cox_pval = cox_summary$coefficients[1, "Pr(>|z|)"],
    logrank_pval = logrank_pval
  )
}

results_combined <- map_dfr(gene_li, fit_models) |> arrange(cox_pval)

write_csv(results_combined, file = "results/bulk/survival_all.csv")

```


```{r}
wrap_plots(plots[results_combined |> filter(cox_pval < 0.05 & logrank_pval < 0.05) |> pull(gene)])


vsd <- read_rds("RData/Bulk/2025-01-28_vsd.rds")

assay(vsd)[,ind_meta] |> 
    as.data.frame() |> 
    tibble::rownames_to_column("gene") |> 
    pivot_longer(cols = -gene, 
                 names_to = "sample",
                 values_to = "expression") |>
    filter(gene == "IL10RB") |> 
    merge(meta, by.x = "sample", by.y = "row.names") |>
    mutate(HCM = if_else(HCM == 1, "CAD", "NCAD")) |> 
    ggplot(aes(x = HCM, y = expression, fill = HCM)) +
    geom_boxplot(width = 0.5) +
    custom_theme()

```































